package GUI;

import Classes.*;
import DAO.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Micael
 */
public class AtualizarPerm extends javax.swing.JFrame {

    private static ArrayList<Users> user = new ArrayList<Users>();
    private static ArrayList<Documentos> documento = new ArrayList<Documentos>();
    private static ArrayList<PermissoesDoc> permissao = new ArrayList<PermissoesDoc>();
    private static String posiUser, posiDoc, posiPerm;
    private static int idUser, idDoc, idPerm;
    DocDAO documentos = new DocDAO();
    PermissoesDocDAO permissoes = new PermissoesDocDAO();
    UsersDAO users = new UsersDAO();

    public AtualizarPerm() {
        setTitle("Atualizar Permissão");
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBoxPerm = new javax.swing.JComboBox<>();
        jButtonA = new javax.swing.JButton();
        jComboBoxPermId = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();
        jComboBoxDoc = new javax.swing.JComboBox<>();
        jComboBoxUsuario = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Documento");

        jLabel5.setText("Usuário");

        jLabel6.setText("Permissão");

        jButton1.setText("Cancelar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxPerm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Editar", "Ver", "Deletar" }));
        jComboBoxPerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPermActionPerformed(evt);
            }
        });

        jButtonA.setText("Atualizar");
        jButtonA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAMouseClicked(evt);
            }
        });
        jButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAActionPerformed(evt);
            }
        });

        jComboBoxPermId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBoxPermId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxPermIdItemStateChanged(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseClicked(evt);
            }
        });

        jComboBoxDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jComboBoxDoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDocItemStateChanged(evt);
            }
        });

        jComboBoxUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jComboBoxUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxUsuarioItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxDoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxPerm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxPermId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBuscar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonA)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addComponent(jComboBoxUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxPermId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuscar)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxPerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonA))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAActionPerformed

    private void jComboBoxPermIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxPermIdItemStateChanged

        posiPerm = String.valueOf(jComboBoxPermId.getSelectedItem());
        PermissoesDocDAO PDDAO = new PermissoesDocDAO();
        permissao = PDDAO.listar();
        for (int i = 0; i < permissao.size(); i++) {
            if (permissao.get(i).getPerm_id() == (Integer.parseInt(posiPerm))) {
                U = permissao.get(i);
            }
        }

    }//GEN-LAST:event_jComboBoxPermIdItemStateChanged

    private void jButtonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseClicked

        try {
            DocDAO ddDAO = new DocDAO();
            UsersDAO uuDAO = new UsersDAO();
            D = ddDAO.procurar(U.getDoc_id());
            jComboBoxDoc.setSelectedItem(D.getTitulo());
            Us = uuDAO.procurar(U.getUser_id());
            jComboBoxUsuario.setSelectedItem(Us.getNome());
        } catch (Exception e) {
            System.out.println("Falha na localização");
        }
        jComboBoxPerm.setSelectedItem(U.getPermission_type());
    }//GEN-LAST:event_jButtonBuscarMouseClicked

    private void jComboBoxDocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDocItemStateChanged
        docchanged();
    }//GEN-LAST:event_jComboBoxDocItemStateChanged
   private void userchanged() {
        posiUser = String.valueOf(jComboBoxUsuario.getSelectedItem());
        UsersDAO UDAO = new UsersDAO();
        user = UDAO.listar();

        for (int i = 0; i < user.size(); i++) {
            if (user.get(i).getNome().equals(posiUser)) {
                Us = user.get(i);
                idUser = Us.getUser_id();  
                break;
            }
        }

    }

    private void docchanged() {
        posiDoc = String.valueOf(jComboBoxDoc.getSelectedItem());
        DocDAO dDAO = new DocDAO();
        documento = dDAO.listar();
        for (int i = 0; i < documento.size(); i++) {
            if (documento.get(i).getTitulo().equals(posiDoc)) {
               idDoc = documento.get(i).getDoc_id();
               break;
            }
        }

    }
    private void jComboBoxUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxUsuarioItemStateChanged

        userchanged();
    }//GEN-LAST:event_jComboBoxUsuarioItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        dispose();

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButtonAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAMouseClicked
        docchanged();
        userchanged();
        U.setDoc_id(idDoc);
        U.setUser_id(idUser);
        U.setPermission_type(jComboBoxPerm.getSelectedItem().toString());

        PermissoesDocDAO UDAO = new PermissoesDocDAO();
        UDAO.atualizar(U);
        JOptionPane.showMessageDialog(rootPane, "- Atualizacao efetuada com sucesso -");
        dispose();
    }//GEN-LAST:event_jButtonAMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        carregaComboDoc();
        carregaComboUser();
        carregaComboPerm();
    }//GEN-LAST:event_formWindowOpened

    private void jComboBoxPermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPermActionPerformed
    public static void carregaComboDoc() {
        jComboBoxDoc.removeAllItems();
        DocDAO dDAO = new DocDAO();
        documento = dDAO.listar();

        for (int i = 0; i < documento.size(); i++) {
            jComboBoxDoc.addItem(documento.get(i).getTitulo());

        }
    }

    public static void carregaComboUser() {
        jComboBoxUsuario.removeAllItems();
        UsersDAO dDAO = new UsersDAO();
        user = dDAO.listar();

        for (int i = 0; i < user.size(); i++) {
            jComboBoxUsuario.addItem(user.get(i).getNome());

        }
    }

    public static void carregaComboPerm() {
        jComboBoxPermId.removeAllItems();
        PermissoesDocDAO dDAO = new PermissoesDocDAO();
        permissao = dDAO.listar();

        for (int i = 0; i < permissao.size(); i++) {
            jComboBoxPermId.addItem(String.valueOf(permissao.get(i).getPerm_id()));

        }
    }

    private Users Us = new Users();
    private Documentos D = new Documentos();
    private PermissoesDoc U = new PermissoesDoc();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonBuscar;
    private static javax.swing.JComboBox<String> jComboBoxDoc;
    private javax.swing.JComboBox<String> jComboBoxPerm;
    private static javax.swing.JComboBox<String> jComboBoxPermId;
    private static javax.swing.JComboBox<String> jComboBoxUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
