package GUI;

import Classes.*;
import DAO.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author Micael
 */
public class AtualizarDoc extends javax.swing.JFrame {

    private static ArrayList<Users> user = new ArrayList<Users>();
    private static ArrayList<DocCategoria> categoria = new ArrayList<DocCategoria>();
    private static ArrayList<Documentos> documento = new ArrayList<Documentos>();
    private static String posiUser, posiCat, posiDoc;
    private static int idUser, idCat;
    DocDAO documentos = new DocDAO();
    DocCategDAO categorias = new DocCategDAO();
    UsersDAO users = new UsersDAO();

    int codigo;

    public AtualizarDoc() {
        setTitle("Atualizar Documento");
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBoxUsuario = new javax.swing.JComboBox<>();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldFilePath = new javax.swing.JTextField();
        jComboBoxDoc = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxCateg = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Documento");

        jLabel2.setText("Usuário");

        jLabel5.setText("Categoria");

        jLabel6.setText("Título");

        jButton1.setText("Atualizar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jComboBoxUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxUsuarioItemStateChanged(evt);
            }
        });

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo", "Arquivado" }));
        jComboBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatusActionPerformed(evt);
            }
        });

        jLabel8.setText("FIle Path");

        jLabel9.setText("Status");

        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });

        jTextFieldFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFilePathActionPerformed(evt);
            }
        });

        jComboBoxDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBoxDoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDocItemStateChanged(evt);
            }
        });
        jComboBoxDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxDocMouseClicked(evt);
            }
        });
        jComboBoxDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDocActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel10.setText("Data de criação");

        jComboBoxCateg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jComboBoxCateg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCategItemStateChanged(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBuscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxUsuario, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(0, 99, Short.MAX_VALUE))
                            .addComponent(jComboBoxDoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxCateg, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFilePath, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscar)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxCateg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatusActionPerformed

    private void jTextFieldFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFilePathActionPerformed

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jComboBoxDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDocActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        carregaComboUser();
        carregaComboDoc();
        carregaComboCateg();

    }//GEN-LAST:event_formWindowOpened

    private void jComboBoxUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxUsuarioItemStateChanged
        userchanged();
    }//GEN-LAST:event_jComboBoxUsuarioItemStateChanged

    private void jComboBoxCategItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCategItemStateChanged
        categchanged();

    }//GEN-LAST:event_jComboBoxCategItemStateChanged

    private void jComboBoxDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxDocMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDocMouseClicked

    private void jComboBoxDocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDocItemStateChanged
        posiDoc = String.valueOf(jComboBoxDoc.getSelectedItem());
        DocDAO dDAO = new DocDAO();
        documento = dDAO.listar();
        int j = 0;
        for (int i = 0; i < documento.size(); i++) {
            if (documento.get(i).getTitulo().equals(posiDoc)) {
                U = documento.get(i);
            }
        }

    }//GEN-LAST:event_jComboBoxDocItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        DateFormat dtOutput = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");

        if (jComboBoxDoc.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Você precisa selecionar um doc!");
        } else if (jTextFieldFilePath.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Você precisa digitar o Diretório!");
        } else {
            userchanged();
            categchanged();
            U.setCateg_id(idCat);
            U.setUser_id(idUser);
            U.setStatus(jComboBoxStatus.getSelectedItem().toString());
            U.setTitulo(jTextFieldTitulo.getText());
            U.setFile_path(jTextFieldFilePath.getText());
            try {
                Date date = dtOutput.parse(jTextField5.getText());
                Timestamp timestamp = new Timestamp(date.getTime());
                U.setData_criacao_doc(timestamp);
            } catch (Exception e) {
                System.out.println("Erro na conversão da data");
            }
            LocalDateTime now = LocalDateTime.now();
            Timestamp timestamp = Timestamp.valueOf(now);
            U.setData_atualizacao_doc(timestamp);
            DocDAO UDAO = new DocDAO();
            UDAO.atualizar(U);
            JOptionPane.showMessageDialog(rootPane, "- Atualização efetuada com sucesso -");
            dispose();
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButtonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseClicked

        try {
            DocCategDAO cDAO = new DocCategDAO();
            UsersDAO uuDAO = new UsersDAO();
            C = cDAO.procurar(U.getCateg_id());
            jComboBoxCateg.setSelectedItem(C.getNome());
            Us = uuDAO.procurar(U.getUser_id());
            jComboBoxUsuario.setSelectedItem(Us.getNome());
        } catch (Exception e) {
            System.out.println("Falha na localização");
        }
        jTextFieldTitulo.setText(U.getTitulo());
        jTextFieldFilePath.setText(U.getFile_path());
        jComboBoxStatus.setSelectedItem(U.getStatus());
        if (U.getData_criacao_doc() == null) {
            jTextField5.setText("");
        } else {
            String aux = "";
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
            aux = sdf.format(U.getData_criacao_doc());
            jTextField5.setText(aux);
        }
    }//GEN-LAST:event_jButtonBuscarMouseClicked

    public static void carregaComboDoc() {
        jComboBoxDoc.removeAllItems();
        DocDAO dDAO = new DocDAO();
        documento = dDAO.listar();

        for (int i = 0; i < documento.size(); i++) {
            jComboBoxDoc.addItem(documento.get(i).getTitulo());

        }
    }

    public static void carregaComboUser() {
        jComboBoxUsuario.removeAllItems();
        UsersDAO dDAO = new UsersDAO();
        user = dDAO.listar();

        for (int i = 0; i < user.size(); i++) {
            jComboBoxUsuario.addItem(user.get(i).getNome());

        }
    }

    public static void carregaComboCateg() {
        jComboBoxCateg.removeAllItems();
        DocCategDAO dDAO = new DocCategDAO();
        categoria = dDAO.listar();

        for (int i = 0; i < categoria.size(); i++) {
            jComboBoxCateg.addItem(categoria.get(i).getNome());

        }
    }

    private void userchanged() {
        posiUser = String.valueOf(jComboBoxUsuario.getSelectedItem());
        UsersDAO UDAO = new UsersDAO();
        user = UDAO.listar();

        for (int i = 0; i < user.size(); i++) {
            if (user.get(i).getNome().equals(posiUser)) {
                Us = user.get(i);
                idUser = Us.getUser_id();  
                break;
            }
        }

    }

    private void categchanged() {
        posiCat = String.valueOf(jComboBoxCateg.getSelectedItem());
        DocCategDAO dcDAO = new DocCategDAO();
        categoria = dcDAO.listar();
        for (int i = 0; i < categoria.size(); i++) {
            if (categoria.get(i).getNome().equals(posiCat)) {
                idCat = categoria.get(i).getCateg_id();
                break;
            }
        }

    }
    private Users Us = new Users();
    private DocCategoria C = new DocCategoria();
    private Documentos U = new Documentos();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBuscar;
    private static javax.swing.JComboBox<String> jComboBoxCateg;
    private static javax.swing.JComboBox<String> jComboBoxDoc;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private static javax.swing.JComboBox<String> jComboBoxUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextFieldFilePath;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
