package GUI;

import Classes.*;
import DAO.*;
import javax.swing.*;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class Main_Listar extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public Main_Listar() {
        setTitle("Página inicial");
        initComponents();
        setResizable(false);
        setSize(500, 300);
        jTabbedPane2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        Ldataad1 = new javax.swing.JList<>();
        jLabel25 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanelUser = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUser = new javax.swing.JTable();
        jPanelDoc = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableDoc = new javax.swing.JTable();
        jPanelPerm = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePerm = new javax.swing.JTable();
        jPanelCateg = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCateg = new javax.swing.JTable();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUser = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        JMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        JMenuDoc = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuPerm = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        JMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        JMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemConfig = new javax.swing.JMenuItem();

        jList6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jList6);

        Ldataad1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(Ldataad1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButton1.setText("Sair");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jTableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableUser);

        javax.swing.GroupLayout jPanelUserLayout = new javax.swing.GroupLayout(jPanelUser);
        jPanelUser.setLayout(jPanelUserLayout);
        jPanelUserLayout.setHorizontalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelUserLayout.setVerticalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Usuarios", jPanelUser);

        jTableDoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableDoc);

        javax.swing.GroupLayout jPanelDocLayout = new javax.swing.GroupLayout(jPanelDoc);
        jPanelDoc.setLayout(jPanelDocLayout);
        jPanelDocLayout.setHorizontalGroup(
            jPanelDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanelDocLayout.setVerticalGroup(
            jPanelDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Documentos", jPanelDoc);

        jTablePerm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablePerm);

        javax.swing.GroupLayout jPanelPermLayout = new javax.swing.GroupLayout(jPanelPerm);
        jPanelPerm.setLayout(jPanelPermLayout);
        jPanelPermLayout.setHorizontalGroup(
            jPanelPermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPermLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanelPermLayout.setVerticalGroup(
            jPanelPermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPermLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Permissões", jPanelPerm);

        jTableCateg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableCateg);

        javax.swing.GroupLayout jPanelCategLayout = new javax.swing.GroupLayout(jPanelCateg);
        jPanelCateg.setLayout(jPanelCategLayout);
        jPanelCategLayout.setHorizontalGroup(
            jPanelCategLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCategLayout.setVerticalGroup(
            jPanelCategLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCategLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        jTabbedPane2.addTab("Categorias", jPanelCateg);

        jToggleButton2.setText("Listar");
        jToggleButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton2ItemStateChanged(evt);
            }
        });
        jToggleButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton2MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jToggleButton2MouseReleased(evt);
            }
        });
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jMenuUser.setText("Usuários");

        jMenuItem6.setText("Inserir");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItem6);

        JMenuItem12.setText("Alterar");
        JMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem12ActionPerformed(evt);
            }
        });
        jMenuUser.add(JMenuItem12);

        jMenuItem8.setText("Excluir");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItem8);

        jMenuBar1.add(jMenuUser);

        JMenuDoc.setText("Documentos");

        jMenuItem1.setText("Inserir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JMenuDoc.add(jMenuItem1);

        jMenuItem2.setText("Alterar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        JMenuDoc.add(jMenuItem2);

        jMenuItem3.setText("Excluir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        JMenuDoc.add(jMenuItem3);

        jMenuBar1.add(JMenuDoc);

        jMenuPerm.setText("Permissões");

        jMenuItem13.setText("Inserir");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenuPerm.add(jMenuItem13);

        JMenuItem13.setText("Alterar");
        JMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem13ActionPerformed(evt);
            }
        });
        jMenuPerm.add(JMenuItem13);

        jMenuItem14.setText("Excluir");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenuPerm.add(jMenuItem14);

        jMenuBar1.add(jMenuPerm);

        jMenu7.setText("Categorias");

        jMenuItem16.setText("Inserir");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem16);

        JMenuItem14.setText("Alterar");
        JMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem14ActionPerformed(evt);
            }
        });
        jMenu7.add(JMenuItem14);

        jMenuItem17.setText("Excluir");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem17);

        jMenuBar1.add(jMenu7);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemConfig.setText("Configurações");
        jMenuItemConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConfigActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemConfig);

        jMenuBar1.add(jMenuFerramentas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(596, 596, 596)
                                .addComponent(jLabel25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jToggleButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(204, 204, 204)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFrame Ins = new InserirDoc();
        Ins.setLocationRelativeTo(rootPane);
        Ins.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFrame Altera = new AtualizarDoc();
        Altera.setLocationRelativeTo(rootPane);
        Altera.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JFrame Exclui = new ExcluirDoc();
        Exclui.setLocationRelativeTo(rootPane);
        Exclui.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JFrame Ins = new InserirUser();
        Ins.setLocationRelativeTo(rootPane);
        Ins.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void JMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem12ActionPerformed
        JFrame Altera = new AtualizarUser();
        Altera.setLocationRelativeTo(rootPane);
        Altera.setVisible(true);
    }//GEN-LAST:event_JMenuItem12ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        JFrame Exclui = new ExcluirUser();
        Exclui.setLocationRelativeTo(rootPane);
        Exclui.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItemConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConfigActionPerformed
        JFrame Conf = new Configuracoes();
        Conf.setLocationRelativeTo(rootPane);
        Conf.setVisible(true);
    }//GEN-LAST:event_jMenuItemConfigActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        JFrame Ins = new InserirPerm();
        Ins.setLocationRelativeTo(rootPane);
        Ins.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void JMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem13ActionPerformed
        JFrame Altera = new AtualizarPerm();
        Altera.setLocationRelativeTo(rootPane);
        Altera.setVisible(true);
    }//GEN-LAST:event_JMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        JFrame Exclui = new ExcluirPerm();
        Exclui.setLocationRelativeTo(rootPane);
        Exclui.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        JFrame Ins = new InserirCategoria();
        Ins.setLocationRelativeTo(rootPane);
        Ins.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void JMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem14ActionPerformed
        JFrame Altera = new AtualizarCategoria();
        Altera.setLocationRelativeTo(rootPane);
        Altera.setVisible(true);
    }//GEN-LAST:event_JMenuItem14ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        JFrame Exclui = new ExcluirCategoria();
        Exclui.setLocationRelativeTo(rootPane);
        Exclui.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MouseReleased

    }//GEN-LAST:event_jToggleButton2MouseReleased

    private void jToggleButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MouseClicked

    }//GEN-LAST:event_jToggleButton2MouseClicked

    private void jToggleButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jToggleButton2ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            jTabbedPane2.setVisible(true);
            setSize(840, 400);
            loadPermTable();
            loadDocTable();
            loadCategTable();
            loadUserTable();
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            jTabbedPane2.setVisible(false);
            setSize(500, 250);
        }
    }//GEN-LAST:event_jToggleButton2ItemStateChanged
    private void loadPermTable() {
        DefaultTableModel tableModel = new DefaultTableModel(
                new Object[][]{},
                new String[]{"ID", "ID Doc", "Documento", "ID User", "Usuário", "Tipo", "Data de Criação"}) {
            boolean[] canEdit = new boolean[]{false, false, false, false, false, false, false};

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        try {
            PermissoesDocDAO CDAO = new PermissoesDocDAO();
            ArrayList<PermissoesDoc> Aux = new ArrayList<PermissoesDoc>();
            Aux = CDAO.listar();
            DocDAO DDAO = new DocDAO();
            UsersDAO UDAO = new UsersDAO();
            tableModel.setRowCount(0);
            ArrayList<Documentos> documento = new ArrayList<Documentos>();
            ArrayList<Users> user = new ArrayList<Users>();
            documento = DDAO.listar();
            user = UDAO.listar();
            if (documento.isEmpty() || user.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Erro: Lista de documentos ou usuários está vazia!");
                return;
            } else {
                for (int l = 0; l < Aux.size(); l++) {
                    PermissoesDoc perm = Aux.get(l);
                    int j = 0, k = 0;
                    for (int i = 0; i < documento.size(); i++) {
                        if (documento.get(i).getDoc_id() == perm.getDoc_id()) {
                            j = i;
                        }
                    }
                    for (int i = 0; i < user.size(); i++) {
                        if (user.get(i).getUser_id() == perm.getUser_id()) {
                            k = i;
                        }
                    }
                    Object[] row = {
                        perm.getPerm_id(),
                        perm.getDoc_id(),
                        documento.get(j).getTitulo(),
                        perm.getUser_id(),
                        user.get(k).getNome(),
                        perm.getPermission_type(),
                        perm.getData_criacao_perm()
                    };
                    tableModel.addRow(row);
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao carregar permissões: " + ex.getMessage());
        }

        jTablePerm.setModel(tableModel);
        jTablePerm.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTablePerm.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTablePerm.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTablePerm.getColumnModel().getColumn(6).setPreferredWidth(200);

    }

    private void loadDocTable() {
        DefaultTableModel docTableModel = new DefaultTableModel(
                new Object[][]{}, new String[]{"ID Doc", "Usuário", "Título", "Categoria", "Diretório", "Status"});

        try {
            DocDAO docDAO = new DocDAO();
            ArrayList<Documentos> Aux = docDAO.listar();
            docTableModel.setRowCount(0);
            UsersDAO UDAO = new UsersDAO();
            ArrayList<Users> user = new ArrayList<Users>();
            user = UDAO.listar();
            DocCategDAO CDAO = new DocCategDAO();
            ArrayList<DocCategoria> categ = new ArrayList<DocCategoria>();
            categ = CDAO.listar();
            int k = 0, j = 0;
            for (Documentos doc : Aux) {
                for (int i = 0; i < user.size(); i++) {
                    if (user.get(i).getUser_id() == doc.getUser_id()) {
                        k = i;
                    }
                }
                for (int i = 0; i < categ.size(); i++) {
                    if (categ.get(i).getCateg_id() == doc.getCateg_id()) {
                        j = i;
                    }
                }
                Object[] row = {
                    doc.getDoc_id(),
                    user.get(k).getNome(),
                    doc.getTitulo(),
                    categ.get(j).getNome(),
                    doc.getFile_path(),
                    doc.getStatus()
                };
                docTableModel.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao carregar documentos: " + e.getMessage());
        }
        jTableDoc.setModel(docTableModel);
        jTableDoc.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableDoc.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableDoc.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTableDoc.getColumnModel().getColumn(4).setPreferredWidth(150);
    }

    private void loadUserTable() {
        DefaultTableModel userTableModel = new DefaultTableModel(
                new Object[][]{}, new String[]{"ID", "Nome", "Email", "Data de Criação", "Cargo"});

        try {
            UsersDAO userDAO = new UsersDAO();
            ArrayList<Users> Aux = userDAO.listar();
            userTableModel.setRowCount(0);

            for (Users user : Aux) {
                Object[] row = {
                    user.getUser_id(),
                    user.getNome(),
                    user.getEmail(),
                    user.getData_criacao(),
                    user.getCargo()
                };
                userTableModel.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao carregar usuários: " + e.getMessage());
        }
        jTableUser.setModel(userTableModel);
        jTableUser.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableUser.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableUser.getColumnModel().getColumn(3).setPreferredWidth(200);

    }

    private void loadCategTable() {
        DefaultTableModel categTableModel = new DefaultTableModel(
                new Object[][]{}, new String[]{"ID Categoria", "Nome", "Descrição"});

        try {
            DocCategDAO categDAO = new DocCategDAO();
            ArrayList<DocCategoria> Aux = categDAO.listar();
            categTableModel.setRowCount(0);

            for (DocCategoria categ : Aux) {
                Object[] row = {
                    categ.getCateg_id(),
                    categ.getNome(),
                    categ.getDescricao()
                };
                categTableModel.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao carregar categorias: " + e.getMessage());
        }
        jTableCateg.setModel(categTableModel);
        jTableCateg.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableCateg.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableCateg.getColumnModel().getColumn(2).setPreferredWidth(300);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf Dark look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        // im not sure if this works
        WindowListener x = new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                System.exit(0);
            }
        };
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame Janela = new Main_Listar();
                Janela.setVisible(true);
                Janela.setLocationRelativeTo(null);
            }
        });
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuDoc;
    private javax.swing.JMenuItem JMenuItem12;
    private javax.swing.JMenuItem JMenuItem13;
    private javax.swing.JMenuItem JMenuItem14;
    private javax.swing.JList<String> Ldataad1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JList<String> jList6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItemConfig;
    private javax.swing.JMenu jMenuPerm;
    private javax.swing.JMenu jMenuUser;
    private javax.swing.JPanel jPanelCateg;
    private javax.swing.JPanel jPanelDoc;
    private javax.swing.JPanel jPanelPerm;
    private javax.swing.JPanel jPanelUser;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableCateg;
    private javax.swing.JTable jTableDoc;
    private javax.swing.JTable jTablePerm;
    private javax.swing.JTable jTableUser;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
